databases:
  - name: microERPdb
    plan: free
    databaseName: microerpdb
    user: microerpdb_user

services:
  - type: web
    plan: free
    name: microERP
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ERPserver.ERPserver.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microERPdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4